from typing import Any

class Unknown: ...

class ExceptionUtil:
    @staticmethod
    def get_traceback(exception: Any): ...
    @staticmethod
    def set_traceback(exception: Any, exc_traceback: Any = ...) -> None: ...
    @classmethod
    def has_traceback(cls, exception: Any): ...
    @classmethod
    def describe(cls, exception: Any, use_traceback: bool = ..., prefix: str = ...): ...

class ChainedExceptionUtil(ExceptionUtil):
    @staticmethod
    def get_cause(exception: Any): ...
    @staticmethod
    def set_cause(exception: Any, exc_cause: Any) -> None: ...
    @classmethod
    def describe(cls, exception: Any, use_traceback: bool = ..., prefix: str = ..., style: str = ...): ...
