from typing import Any, Optional

def iscoroutinefunction(func: Any): ...
def is_context_manager(func: Any): ...

class InvalidFixtureError(RuntimeError): ...

def use_fixture(fixture_func: Any, context: Any, *fixture_args: Any, **fixture_kwargs: Any): ...
def use_fixture_by_tag(tag: Any, context: Any, fixture_registry: Any): ...
def fixture_call_params(fixture_func: Any, *args: Any, **kwargs: Any): ...
def use_composite_fixture_with(context: Any, fixture_funcs_with_params: Any): ...
def fixture(func: Optional[Any] = ..., name: Optional[Any] = ..., pattern: Optional[Any] = ...): ...
