from behave import model as model
from behave.model_core import Status as Status
from typing import Any

def parse(json_filename: Any, encoding: str = ...): ...

class JsonParser:
    current_scenario_outline: Any = ...
    def __init__(self) -> None: ...
    def parse_features(self, json_data: Any): ...
    def parse_feature(self, json_feature: Any): ...
    def add_feature_element(self, feature: Any, json_element: Any) -> None: ...
    def parse_background(self, json_element: Any): ...
    def parse_scenario(self, json_element: Any): ...
    def parse_scenario_outline(self, json_element: Any): ...
    def parse_steps(self, json_steps: Any): ...
    def parse_step(self, json_element: Any): ...
    @staticmethod
    def add_step_result(step: Any, json_result: Any) -> None: ...
    @staticmethod
    def parse_table(json_table: Any): ...
    def parse_examples(self, json_element: Any): ...
