from typing import Any

class TagExpression:
    ands: Any = ...
    limits: Any = ...
    def __init__(self, tag_expressions: Any) -> None: ...
    @staticmethod
    def normalize_tag(tag: Any): ...
    @classmethod
    def normalized_tags_from_or(cls, expr: Any) -> None: ...
    def store_and_extract_limits(self, tags: Any) -> None: ...
    def check(self, tags: Any): ...
    def __len__(self): ...
