from typing import Any, Optional

BEHAVE_UNICODE_ERRORS: Any

def make_indentation(indent_size: Any, part: str = ...): ...
def indent(text: Any, prefix: Any): ...
def compute_words_maxsize(words: Any): ...
def is_ascii_encoding(encoding: Any): ...
def select_best_encoding(outstream: Optional[Any] = ...): ...
def text(value: Any, encoding: Optional[Any] = ..., errors: Optional[Any] = ...): ...
def to_texts(args: Any, encoding: Optional[Any] = ..., errors: Optional[Any] = ...): ...
def ensure_stream_with_encoder(stream: Any, encoding: Optional[Any] = ...): ...
