from typing import Any

def register_as(formatter_class: Any, name: Any) -> None: ...
def register(formatter_class: Any) -> None: ...
def get_formatter(config: Any, stream_openers: Any): ...
def setup_formatters() -> None: ...
