from behave.formatter.base import Formatter as Formatter
from behave.model_core import Status as Status
from typing import Any

class RerunFormatter(Formatter):
    name: str = ...
    description: str = ...
    show_timestamp: bool = ...
    show_failed_scenarios_descriptions: bool = ...
    failed_scenarios: Any = ...
    current_feature: Any = ...
    def __init__(self, stream_opener: Any, config: Any) -> None: ...
    def reset(self) -> None: ...
    def feature(self, feature: Any) -> None: ...
    def eof(self) -> None: ...
    stream: Any = ...
    def close(self) -> None: ...
    def report_scenario_failures(self) -> None: ...
