from behave.textutil import compute_words_maxsize as compute_words_maxsize
from typing import Any, Optional

class DocumentWriter:
    heading_styles: Any = ...
    default_encoding: str = ...
    default_toctree_title: str = ...
    stream: Any = ...
    filename: Any = ...
    should_close: Any = ...
    def __init__(self, stream: Any, filename: Optional[Any] = ..., should_close: bool = ...) -> None: ...
    @classmethod
    def open(cls, filename: Any, encoding: Optional[Any] = ...): ...
    def write(self, *args: Any): ...
    def close(self) -> None: ...
    def write_heading(self, heading: Any, level: int = ..., index_id: Optional[Any] = ..., label: Optional[Any] = ...) -> None: ...
    def write_toctree(self, entries: Any, title: Optional[Any] = ..., maxdepth: int = ...) -> None: ...
    def write_table(self, table: Any) -> None: ...
