from behave.model_core import Status as Status
from typing import Any

class Reporter:
    config: Any = ...
    def __init__(self, config: Any) -> None: ...
    def feature(self, feature: Any) -> None: ...
    def end(self) -> None: ...
