from .steps import StepsUsageFormatter as StepsUsageFormatter
from behave.runner_util import make_undefined_step_snippets as make_undefined_step_snippets
from typing import Any

STEP_MODULE_TEMPLATE: str

class MissingStepsFormatter(StepsUsageFormatter):
    name: str = ...
    description: str = ...
    template: Any = ...
    scope: str = ...
    def __init__(self, stream_opener: Any, config: Any) -> None: ...
    def init_from_userdata(self, userdata: Any) -> None: ...
    stream: Any = ...
    def close(self) -> None: ...
    def report(self) -> None: ...
